### ISSUE TITLE
TypeError: Cannot read property 'return' of undefined

### ISSUE THREAD

**Issue by joluHo** [eris-ltd/eris-contracts.js#39]
- [ ] docker version - 1.12.1
- [ ] eris version - 0.12.0-rc3
- [ ] eris-contracts version - 0.13.3
- [ ] go version - go1.6.3
- [ ] docker-machine version - 0.7.0
- [ ] OS - linux/amd64 

Cannot interact with smart contracts. 
I'm having this as response from any contract interaction.
```
Market contract address is: C2D0A83CE0F6FEE5BCD6832B3F4CDD214D0FD318
/home/jose/.eris/apps/Market/node_modules/eris-contracts/lib/pipes/dev_pipe.js:98
                callback(null, data.return);
                                   ^

TypeError: Cannot read property 'return' of undefined
    at /home/jose/.eris/apps/Market/node_modules/eris-contracts/lib/pipes/dev_pipe.js:98:36
    at /home/jose/.eris/apps/Market/node_modules/eris-contracts/node_modules/eris-db/lib/transactions.js:176:9
    at fixedCallback (/home/jose/.eris/apps/Market/node_modules/eris-contracts/node_modules/eris-db/lib/unsafe.js:120:13)
    at /home/jose/.eris/apps/Market/node_modules/eris-contracts/node_modules/eris-db/lib/rpc/http.js:81:13
    at httpRequest.onreadystatechange (/home/jose/.eris/apps/Market/node_modules/eris-contracts/node_modules/eris-db/lib/rpc/http.js:103:17)
    at dispatchEvent (/home/jose/.eris/apps/Market/node_modules/eris-contracts/node_modules/eris-db/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:572:25)
    at setState (/home/jose/.eris/apps/Market/node_modules/eris-contracts/node_modules/eris-db/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:14)
    at IncomingMessage.<anonymous> (/home/jose/.eris/apps/Market/node_modules/eris-contracts/node_modules/eris-db/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:431:13)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
```
The script i'm using to interact is the following:

```
// requires
var fs = require ('fs');
var prompt = require('prompt');
var erisC = require('eris-contracts');

var erisdbURL = "http://localhost:33131/rpc";
// get the abi and deployed data squared away
var contractData = require('./jobs_output.json');
var MarketContractAddress = contractData["deployMarket"];
var MarketAbi = JSON.parse(fs.readFileSync("./abi/Market"));
// properly instantiate the contract objects manager using the erisdb URL
// and the account data (which is a temporary hack)
var accountData = require('./account.json');
var contractsManager = erisC.newContractManagerDev(erisdbURL, accountData);

// properly instantiate the contract objects using the abi and address
var MarketContract;
contractsManager.newContractFactory(MarketAbi).at(MarketContractAddress, function(error, contract){
    if (error) {
        // Something.
        throw error;
    }
    MarketContract = contract;
});

function instantiate() {
  console.log("Market contract address is: " + MarketContractAddress);
  MarketContract.initMarket(function(error, result){
    if (error) {
      console.log("Error calling MarketContract");
      throw error;
    } else {
      console.log("Contract addresses are:\n" + "oBook:\t" + result[3] + "\noMatch:\t" + result[4]);
    }
  });
}

// run
instantiate();

```

The epm manages to call that function during deployment.
```
jobs:

- name: deployMarket
  job:
    deploy:
      contract: Market.sol
      instance: all
      wait: true

- name: initMarket
  job:
    call:
      destination: $deployMarket
      function: initMarket
      abi: Market
      wait: true
```

Retourning the following:
```
{
  "defaultAddr": "348B10C3D9246131ADCB3542BA1CDC9B13D692C",
  "deployMarket": "C2D0A83CE0F6FEE5BCD6832B3F4CDD214D0FD318",
  "initMarket": "[82237A5381E4CD75B150E288774CF851A7127C08,4CB3542BA1CDC9B13FF912B19C43C686605BEDA6,31C582D706EC2C3FA7D6921569FB611AFC411B75,657261863B50DE8B10C3D9246131ADBA8ED89D77,B3C62230AA494EAE511B26DDD8E75E7BB2F88F5D]"
}
```

Notice that I didn't have this issue with eris-cli 0.12.0-rc2. I was able to interact with the same scripts and smart contracts.

Here is the log of the chain with the tx being executed without errors:
https://gist.github.com/joluHo/8770df36528ffd3ef6970247d7c5e70d

**Comment by joluHo** [comment]
I think I found the problem.
In `/home/jose/.eris/apps/Market/node_modules/eris-contracts/node_modules/eris-db/lib/unsafe.js:119:13` there is a bug in the assignment `data2 = data2[1]`.
The function should retourn `data2` instead of `data2[1]` so the function `transactAndHold` can decide wether to return the result or the callee:

```
    this._erisdb.txs().transactAndHold(from, to, txPayload.data, config.DEFAULT_GAS, config.DEFAULT_FEE, null, function (error, data) {
        if (error) {
            console.log(error);
            callback(error);
        } else {
            if(to) {
                callback(null, data.return);

            } else {
                callback(null, data.call_data.callee);
            }
        }
    });
```

If I comment the corresponding line it works for me

**Comment by NodeGuy** [comment]
The problem is that you're trying to use the released version of eris-contracts.js with the unreleased version of eris-db.  They're not compatible.  Please use eris-db 0.11 or wait for 0.12 to be released.
