### ISSUE TITLE
Iteray module missing from dependency list in npm module

### ISSUE THREAD

**Issue by rguikers** [eris-ltd/eris-contracts.js#43]
version 0.15.2 is missing iteray module as a dependency. It is however added to the dev dependencies, but this creates a problem with NPM

```
Error: Cannot find module 'iteray'
[0]     at Function.Module._resolveFilename (module.js:469:15)
[0]     at Function.Module._load (module.js:417:25)
[0]     at Module.require (module.js:497:17)
[0]     at require (internal/module.js:20:19)
[0]     at Object.<anonymous> (/Users/rguikers/develop/ppu/ppugui/node_modules/eris-contracts/lib/contractManager.js:9:11)
[0]     at Module._compile (module.js:570:32)
[0]     at Object.Module._extensions..js (module.js:579:10)
[0]     at Module.load (module.js:487:32)
[0]     at tryModuleLoad (module.js:446:12)
[0]     at Function.Module._load (module.js:438:3)
[0]     at Module.require (module.js:497:17)
[0]     at require (internal/module.js:20:19)
[0]     at Object.<anonymous> (/Users/rguikers/develop/ppu/ppugui/node_modules/eris-contracts/index.js:1:85)
```

temporary workaround is installing it manually (npm i iteray --save)

**Comment by NodeGuy** [comment]
Fixed in 0.15.3.
