### ISSUE TITLE
address as a parameter results in Bignumber error

### ISSUE THREAD

**Issue by rguikers** [eris-ltd/eris-contracts.js#44]
Hi, 

When using an address as a parameter in version 0.15.2 we get an exception : 

```
0] BigNumber Error: new BigNumber() not a number: 88977A37D05A4FE86D09E88C88A49C2FCF7D6D8F
[0]     at raise (/Users/rguikers/develop/ppu/ppugui/node_modules/eris-contracts/node_modules/web3/node_modules/bignumber.js/bignumber.js:1177:25)
[0]     at /Users/rguikers/develop/ppu/ppugui/node_modules/eris-contracts/node_modules/web3/node_modules/bignumber.js/bignumber.js:1165:33
[0]     at new BigNumber (/Users/rguikers/develop/ppu/ppugui/node_modules/eris-contracts/node_modules/web3/node_modules/bignumber.js/bignumber.js:193:67)
[0]     at new BigNumber (/Users/rguikers/develop/ppu/ppugui/node_modules/eris-contracts/node_modules/web3/node_modules/bignumber.js/bignumber.js:203:25)
[0]     at toBigNumber (/Users/rguikers/develop/ppu/ppugui/node_modules/eris-contracts/node_modules/web3/lib/utils/utils.js:367:12)
[0]     at Object.toTwosComplement (/Users/rguikers/develop/ppu/ppugui/node_modules/eris-contracts/node_modules/web3/lib/utils/utils.js:378:21)
[0]     at SolidityTypeAddress.formatInputInt [as _inputFormatter] (/Users/rguikers/develop/ppu/ppugui/node_modules/eris-contracts/node_modules/web3/lib/solidity/formatters.js:40:38)
[0]     at SolidityTypeAddress.SolidityType.encode (/Users/rguikers/develop/ppu/ppugui/node_modules/eris-contracts/node_modules/web3/lib/solidity/type.js:179:17)
[0]     at /Users/rguikers/develop/ppu/ppugui/node_modules/eris-contracts/node_modules/web3/lib/solidity/coder.js:86:29
[0]     at Array.map (native)
[0]     at SolidityCoder.encodeParams (/Users/rguikers/develop/ppu/ppugui/node_modules/eris-contracts/node_modules/web3/lib/solidity/coder.js:85:34)
[0]     at SolidityFunction.toPayload (/Users/rguikers/develop/ppu/ppugui/node_modules/eris-contracts/node_modules/web3/lib/web3/function.js:69:52)
[0]     at SolidityFunction.call (/Users/rguikers/develop/ppu/ppugui/node_modules/eris-contracts/node_modules/web3/lib/web3/function.js:108:24)
[0]     at SolidityFunction.call (/Users/rguikers/develop/ppu/ppugui/node_modules/eris-contracts/lib/contractManager.js:82:38)
[0]     at SolidityFunction.execute (/Users/rguikers/develop/ppu/ppugui/node_modules/eris-contracts/node_modules/web3/lib/web3/function.js:223:22)
```

**Comment by NodeGuy** [comment]
Fixed in 0.15.3.
