### ISSUE TITLE
Unable to start eris service

### ISSUE THREAD

**Issue by somak12** [eris-ltd/eris-contracts.js#52]
I have tried in new eris 0.12.0, using eris-contract.js 0.15.6 during npm it gives error 'UNMET PEER DEPENDENCY request@^2.34'

When I try to do node app.js (Unable to start eris service) it gives error 

/usr/src/app/node_modules/eris-contracts/lib/contractManager.js:108
const wrapMethod = (name, outputUnpacker = R.identity) =>
^

SyntaxError: Unexpected token =
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:373:25)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object. (/usr/src/app/node_modules/eris-contracts/index.js:1:85)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)

Node : 6.9.1
npm: 3.10.8

**Comment by somak12** [comment]
This was a mistake from my end. Eris service is working properly now. For guys who are migrating please don't  forget to update the Dockerfile to node:6- onbuild else the service wont work for new eris 0.12.0.

**Comment by NodeGuy** [comment]
I'm glad you got it working.
