### ISSUE TITLE
Encoding IPFS hash string to Solidity problem

### ISSUE THREAD

**Issue by marc4gov** [eris-ltd/eris-contracts.js#53]
I used to save the IPFS hash in a `string fileHash` in a Solidity contract in Eris 0.11.4. Somehow it's broken now:

```
req.file:  { fieldname: 'fileUpload',
  originalname: 'style.css',
  encoding: '7bit',
  mimetype: 'text/css',
  destination: 'uploads/',
  filename: '59c4b1099aa906c7d29729182d701c91',
  path: 'uploads/59c4b1099aa906c7d29729182d701c91',
  size: 1499 }
IPFS result:  QmNUw5eJKfAT3dM4ecQFULjpuXQvg9CQFA93XiVEbTzZ3S
/Users/marc/Documents/HerenBouw/node_modules/eris-contracts/node_modules/utf8/utf8.js:26
		var length = string.length;
		                   ^

TypeError: Cannot read property 'length' of undefined
    at ucs2decode (/Users/marc/Documents/HerenBouw/node_modules/eris-contracts/node_modules/utf8/utf8.js:26:22)
    at Object.utf8encode [as encode] (/Users/marc/Documents/HerenBouw/node_modules/eris-contracts/node_modules/utf8/utf8.js:104:20)
    at Object.fromUtf8 (/Users/marc/Documents/HerenBouw/node_modules/eris-contracts/node_modules/web3/lib/utils/utils.js:152:16)
    at SolidityTypeString.formatInputString [as _inputFormatter] (/Users/marc/Documents/HerenBouw/node_modules/eris-contracts/node_modules/web3/lib/solidity/formatters.js:81:24)
    at SolidityTypeString.SolidityType.encode (/Users/marc/Documents/HerenBouw/node_modules/eris-contracts/node_modules/web3/lib/solidity/type.js:179:17)
    at /Users/marc/Documents/HerenBouw/node_modules/eris-contracts/node_modules/web3/lib/solidity/coder.js:86:29
    at Array.map (native)
    at SolidityCoder.encodeParams (/Users/marc/Documents/HerenBouw/node_modules/eris-contracts/node_modules/web3/lib/solidity/coder.js:85:34)
    at SolidityFunction.toPayload (/Users/marc/Documents/HerenBouw/node_modules/eris-contracts/node_modules/web3/lib/web3/function.js:69:52)
    at SolidityFunction.sendTransaction (/Users/marc/Documents/HerenBouw/node_modules/eris-contracts/node_modules/web3/lib/web3/function.js:130:24)
    at SolidityFunction.sendTransaction (/Users/marc/Documents/HerenBouw/node_modules/eris-contracts/lib/contractManager.js:121:38)
    at SolidityFunction.execute (/Users/marc/Documents/HerenBouw/node_modules/eris-contracts/node_modules/web3/lib/web3/function.js:219:37)
    at ipfs.util.addFromFs (/Users/marc/Documents/HerenBouw/routes/orders.js:175:45)
```

This is the node function causing the issue:

```
router.post('/task/:taskAddress', upload.single('fileUpload'), function(req, res) {
  var desc = req.body.desc;
  var amount = Number(req.body.amount);
  var terms = Number(req.body.terms);
  var taskAddress = req.params.address;
  var tmp_path = req.file.path;
  var target_path = 'uploads/' + req.file.originalname;
  console.log("req.file: ", req.file);

  ipfs.util.addFromFs(req.file.path, { recursive: false }, (err, result) => {
      if (err) {
          throw err
      }
      console.log("IPFS result: ", result[0].hash);
      var fileHash = result[0].hash;

      return Blockchain.taskmanagerContract.addTaskOrder(
                  taskAddress,
                  eriswrapper.str2hex(desc),
                  amount,
                  terms,
                  eriswrapper.str2hex(req.file.originalname),
                  fileHash,
                  addOrderToTaskCallback
              );
  });

  function addOrderToTaskCallback(err, result) {
      if (err) {
          console.log("Error in adding order to task: ", err);
          console.error(err);
      }
      res.redirect('/orders/task/'+taskAddress);
  }

});
```

As you can see, I use the eriswrapper helper function (from the eris hello example) to encode in hex. Have a feeling it's in the encoding, however I tried with/without hexing but then the call obviously fails on formatting reasons.

**Comment by NodeGuy** [comment]
Please submit the code for the Solidity function `addTaskOrder` or at least its signature.

**Comment by marc4gov** [comment]
TaskManager contract function:
```
    function addTaskOrder(address taskAddress, bytes32 desc, uint cost, uint terms, string fileName, string fileHash)
    returns (address) {
        Task t = Task(taskAddress);
        address order = t.addOrder(desc, cost, terms, fileName, fileHash);
        uint eventID = xAddEvent(hist, "Task Order added");
        OrderAdded(taskAddress, desc, cost, terms, fileName, fileHash, eventID);
        return order;
    }
```

Task contract
```
    function addOrder(bytes32 desc, uint amount, uint terms, string fileName, string fileHash)
    returns (address) {
      Order o = new Order(desc, amount, terms, fileName, fileHash);
      orderList.addElement(o, desc);
      return address(o);
    }
```

Order contract first part
```
import "owned.sol";
import "tracker.sol";

contract Order is tracker, owned {

    uint8 constant APPROVED = 1;
    uint8 constant INPROGRESS = 2;
    uint8 constant ADDED = 0;
    uint8 constant READY = 3;
    uint8 constant PAYED = 4;

    address owner;
    string fileName;
    string fileHash;
    uint time;
    uint amount;
    bytes32 public desc;
    uint terms;
    address approvedBy;

    struct invoice {
        string fileName;
        string fileHash;
        uint time;
        uint term_nr;
        uint amount;
        address approvedBy;
    }

    mapping(uint => invoice) invoices;
    uint public last_invoice_id = 0;
    history hist;
    uint8 public status = ADDED;

    event InvoiceAdded(address orderAddress, uint term_nr, uint eventID);
    event InvoiceApproved(address orderAddress, address confirmer, uint term_nr, uint eventID);

    function Order(bytes32 _desc, uint _amount, uint _terms, string _fileName, string _fileHash) onlyOwner {
        owner = msg.sender;
        desc = _desc;
        approvedBy = address(0x0);
        amount = _amount;
        terms = _terms;
        time = now;
        fileName = _fileName;
        fileHash = _fileHash;
    }
```

**Comment by NodeGuy** [comment]
Please add the following line before `return Blockchain.taskmanagerContract.addTaskOrder(` so we can see what the arguments that are causing the error look like:

```JavaScript
console.log(
  taskAddress,
  eriswrapper.str2hex(desc),
  amount,
  terms,
  eriswrapper.str2hex(req.file.originalname),
  fileHash
)
```

**Comment by marc4gov** [comment]
I think you can close this one. I don't need the Eris wrapper for strings anymore I noticed. I removed it and then it works as expected
