### ISSUE TITLE
SyntaxError: Unexpected token = 

### ISSUE THREAD

**Issue by tprafull** [eris-ltd/eris-contracts.js#67]
Version details 
Eris CLI Version: 0.12.0 (002c63e)
eris-contracts  "0.15.8" 

# Issue Description
I was not able to run contract on eris 0.11 version. I upgraded eris to 0.12 and then updated eris-contracts to latest. 

I am getting  this error after running node program.

/home/demoadmin/node_modules/eris-contracts/lib/contractManager.js:107
  const wrapMethod = (name, outputUnpacker = R.identity) =>
                                           ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/demoadmin/node_modules/eris-contracts/index.js:                                             1:85)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by NodeGuy** [comment]
Please upgrade to Node.js version 6 or above.

**Comment by tprafull** [comment]
Thanks for response. I updated node.js to version v6.9.4. I am getting different error now. I want to upload a file to IPFS and generate unique ID by passing IPFS hash. When I executed my node program, I got below error. 

```
{ Error: Error broadcasting transaction: Unknown error returned: Duplicate transaction (ignored)
    at values.next.then (/home/demoadmin/node_modules/eris-contracts/node_modules/eris-db/node_modules/@nodeguy/json-rpc/lib/index.js:12:38)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
    at Function.module.exports.loopWhile (/home/demoadmin/node_modules/deasync/index.js:71:11)
    at Function.sleep (/home/demoadmin/node_modules/deasync/index.js:44:19)
    at hexifyAuditdata (/home/demoadmin/Prafull/auditpoc/nodeserver.js:158:32)
    at /home/demoadmin/Prafull/auditpoc/nodeserver.js:669:25
    at Layer.handle [as handle_request] (/home/demoadmin/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/demoadmin/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/demoadmin/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/demoadmin/node_modules/express/lib/router/layer.js:95:5)
    at /home/demoadmin/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/demoadmin/node_modules/express/lib/router/index.js:330:12)
    at next (/home/demoadmin/node_modules/express/lib/router/index.js:271:10)
    at /home/demoadmin/Prafull/auditpoc/nodeserver.js:39:5
    at Layer.handle [as handle_request] (/home/demoadmin/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/demoadmin/node_modules/express/lib/router/index.js:312:13)
    at /home/demoadmin/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/demoadmin/node_modules/express/lib/router/index.js:330:12)
    at next (/home/demoadmin/node_modules/express/lib/router/index.js:271:10)
    at Immediate.<anonymous> (/usr/lib/node_modules/multer/lib/make-middleware.js:52:37)
    at runCallback (timers.js:653:20)
    at tryOnImmediate (timers.js:622:5)
  method: 'transactAndHold',
  params:
   [ { priv_key: '811D3FA47CA5767821E15A58B072717D43974474E25E9765D20968D1B6C41066C78D187712835A5034D5A216EA8686601218E88DF6FF15E81AA08AB79AB7CC04',
       address: '7EE9EB8B85FAD66EC31D1FFA74EB994D44C2ABEA',
       data: 'f39b2368000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000002e516d56555451677053787072354c68766b48386b5448473948355745344671437a44576264535a706734534c5a69000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003d42616c616e6365205368656574092232372046656272756172792032303136efbfbd6d22092232382046656272756172792032303135efbfbd6d220909000000',
       gas_limit: 1000000,
       fee: 0 } ],
  code: -32603,
  message: 'Error broadcasting transaction: Unknown error returned: Duplicate transaction (ignored)' }
Error in converting records Error: Error broadcasting transaction: Unknown error returned: Duplicate transaction (ignored)
```
